feat: add support for move next and previous files in harpooner list
erotourtes/Harpooner pull request #21
Opened 2024-06-14 16:17 UTC by marzelwidmer

Inspiration from theprimeagen.

Move to next and previous file in the list

2024-06-15 10:19 UTC, erotourtes commented
Hi, @marzelwidmer! Thank you for the PR. I'll make a release after the merge and after JetBrains approval, which takes up to 2 working days, changes will be available in the store

2024-06-15 10:38 UTC, erotourtes requested changes

2024-06-15 10:38 UTC, erotourtes commented on src/main/kotlin/com/github/erotourtes/harpoon/services/HarpoonService.kt
> +import com.maddyhome.idea.vim.regexp.Magic.i
there is an unused import

2024-06-15 10:38 UTC, erotourtes commented on src/main/resources/META-INF/plugin.xml
> +        <action id="NextFileAction"
I should've added some guidelines to the project. It would be great to prefix all the actions like `HarpoonerNextFileAction` with Harpooner. I'll then document this action in the `readme`.

2024-06-15 10:38 UTC, erotourtes commented on src/main/resources/META-INF/plugin.xml
> +        <action id="PreviousFileAction"
this one as well `HarpoonerPreviousFileAction`

2024-06-17 09:26 UTC, marzelwidmer commented
Impl. your feedback.

2024-06-17 18:24 UTC, erotourtes approved these changes

2024-06-17 18:38 UTC, merged